#!/bin/sh

defaultSln=`git config open.default`
unix=`date +%s`
if [[ $1 == "help" ]]; then
	echo "Creates versioned nuget packages for all projects in a solution marked as IsPackable=true"
	echo ""
	echo "git pack-local {version} {sln} {output-directory} {args}"
	echo
	echo -e "  version:"
	echo -e "    The desired nuget package version number - defaults to 'ci-$unix'"
	echo ""
	echo -e "  sln:"
	echo -e "    Relative path to the solution file - defaults to $defaultSln"
	echo
	echo -e "  output-directory:"
	echo -e "    The directory where packages will be placed - defaults to /c/src/1konto/packages/`basename -s .sln $defaultSln`"
	echo
	echo -e "  args:"
	echo -e "    Additional arguments to pass, by default -c Debug and --include-symbols are used"
	echo
	echo
	echo "  Executed Command:"
	echo -e "    dotnet pack -c Debug --include-symbols -p:Version=$version $args -o $output $sln"
	echo
	echo "  Some use cases:"
	echo
	echo -e "  Package heman assemblies in debug mode for faster iteration"
	echo -e "    git pack-local 16.2.0 ./src/heman.sln /c/src/1konto/packages/heman"
	exit 0
fi

sln=${2:-$defaultSln}

version=${1:-0.0.0-ci-$unix}

dir=`basename -s .sln $defaultSln`
output=${3:-/c/src/1konto/packages/$dir}

args=${4:-}

echo
echo "dotnet pack -c Debug --include-symbols -p:Version=$version $args -o $output $sln"
echo

dotnet pack -c Debug --include-symbols -p:Version=$version $args -o $output $sln

echo
echo "Packaged version $version saved to $output"